# Generated by Django 4.1.8 on 2024-01-23 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10, verbose_name='Базовая валютa')),
                ('current_currency', models.CharField(db_index=True, max_length=10, verbose_name='Текущая валюта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Текущее время')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ('timestamp',),
            },
        ),
    ]
